import { convertToUSDateTime } from "../utils";

export const appointments = [
    {
        id: "1",
        firstName: "James",
        middleName: "Joy",
        lastName: "Rodriguez",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: new Date().toISOString(),
        status: "Attended",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "2",
        firstName: "Adam",
        middleName: "Joy",
        lastName: "Smith",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Missed",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "3",
        firstName: "Bukola",
        middleName: "Joy",
        lastName: "Almarouf",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Upcoming",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "4",
        firstName: "Mushrif",
        middleName: "Joy",
        lastName: "Ajayi",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Attended",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "5",
        firstName: "Isabella",
        middleName: "Joy",
        lastName: "Evans",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Missed",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "6",
        firstName: "Bukola",
        middleName: "Joy",
        lastName: "Almarouf",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Upcoming",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "7",
        firstName: "Mushrif",
        middleName: "Joy",
        lastName: "Ajayi",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Attended",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "8",
        firstName: "Isabella",
        middleName: "Joy",
        lastName: "Evans",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Missed",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "9",
        firstName: "Bukola",
        middleName: "Joy",
        lastName: "Almarouf",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Upcoming",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "10",
        firstName: "Mushrif",
        middleName: "Joy",
        lastName: "Ajayi",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Attended",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "11",
        firstName: "Isabella",
        middleName: "Joy",
        lastName: "Evans",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Missed",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "12",
        firstName: "Bukola",
        middleName: "Joy",
        lastName: "Almarouf",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Upcoming",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "13",
        firstName: "Mushrif",
        middleName: "Joy",
        lastName: "Ajayi",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Attended",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "14",
        firstName: "Isabella",
        middleName: "Joy",
        lastName: "Evans",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab0",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Upcoming",
        purpose: "To resolve bipolar disorder and lack of concntration",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    // Add more data here
];

export const appointmentsColumns = [
    {
        accessorKey: "firstName",
        header: "First Name",
    },
    {
        accessorKey: "lastName",
        header: "Last Name",
    },
    {
        accessorKey: "dateTime",
        header: "Appointment Date",
        cell: (prop) => `${convertToUSDateTime(prop.getValue(), true)} ET`,
    },
    {
        accessorKey: "phone",
        header: "Phone",
    },
    {
        accessorKey: "email",
        header: "Email",
    },
    {
        accessorKey: "status",
        header: "Status",
        cell: (prop) => {
            const value = prop.getValue();

            return (
                <span
                    className={`p-1 w-20 block text-center rounded text-xs text-offWhite capitalize ${
                        value.toLowerCase() === "attended"
                            ? "bg-lightGreen"
                            : value.toLowerCase() === "upcoming"
                            ? "bg-yellow-700"
                            : value.toLowerCase() === "missed"
                            ? "bg-vividRed"
                            : ""
                    }`}
                >
                    {value}
                </span>
            );
        },
    },
];
