export const patients = [
    {
        id: "PAT0000001",
        firstName: "James",
        lastName: "Rodriguez",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "rodrijay@gmail.com",
    },
    {
        id: "PAT0000002",
        firstName: "Adam",
        lastName: "Smith",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "smith97dams@gmail.com",
    },
    {
        id: "PAT0000003",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000004",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000005",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000003",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000004",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000005",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000003",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000004",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000005",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000003",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000004",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000005",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000003",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000004",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000005",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    // Add more data here
];

export const patientsColumns = [
    {
        accessorKey: "id",
        header: "Patient ID",
    },
    {
        accessorKey: "firstName",
        header: "First Name",
    },
    {
        accessorKey: "lastName",
        header: "Last Name",
    },
    {
        accessorKey: "dob",
        header: "Date of Birth",
    },
    {
        accessorKey: "gender",
        header: "Gender",
    },
    {
        accessorKey: "phone",
        header: "Phone",
    },
    {
        accessorKey: "email",
        header: "Email",
    },
];