export const patients = [
    {
        id: "PAT0000001",
        firstName: "James",
        lastName: "Rodriguez",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "rodrijay@gmail.com",
    },
    {
        id: "PAT0000002",
        firstName: "Adam",
        lastName: "Smith",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "smith97dams@gmail.com",
    },
    {
        id: "PAT0000003",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000004",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000005",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000006",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000007",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000008",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000009",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000010",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000011",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000012",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000013",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000014",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    {
        id: "PAT0000015",
        firstName: "Bukola",
        lastName: "Almarouf",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "marouf_buk@gmail.com",
    },
    {
        id: "PAT0000016",
        firstName: "Mushrif",
        lastName: "Ajayi",
        dob: new Date("03/21/1974").toLocaleDateString(),
        gender: "Male",
        phone: "+4104567891",
        email: "mushajayi@gmail.com",
    },
    {
        id: "PAT0000017",
        firstName: "Isabella",
        lastName: "Evans",
        dob: new Date("03/21/1960").toLocaleDateString(),
        gender: "Female",
        phone: "+4104567891",
        email: "isbevans@gmail.com",
    },
    // Add more data here
];

export const patientsColumns = [
    {
        accessorKey: "patientId",
        header: "Patient ID",
    },
    {
        accessorKey: "firstName",
        header: "First Name",
    },
    {
        accessorKey: "lastName",
        header: "Last Name",
    },
    {
        accessorKey: "dob",
        header: "Date of Birth",
    },
    {
        accessorKey: "gender",
        header: "Gender",
    },
    {
        accessorKey: "phone",
        header: "Phone",
    },
    {
        accessorKey: "email",
        header: "Email",
    },
];

export const patientsList = [
    {
        id: "PAT0000001",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "",
            // middleName: "",
            lastName: "",
            dob: "",
            relationship: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "",
            // middleName: "",
            lastName: "",
            gender: "",
            maritalStatus: "",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "",
            // middleName: "",
            lastName: "",
            relationship: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000002",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000003",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Master's Degree",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widowed",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000004",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000005",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "Michelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000006",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000007",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000008",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000009",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Self Pay",
            primaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coPay: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "",
                    middleName: "",
                    lastName: "",
                    relationship: "",
                    phone: "",
                    dob: "",
                },
                insuranceProvider: {
                    name: "",
                    phone: "",
                    policyId: "",
                    groupNumber: "",
                    authorizationId: "",
                    coverageStartDate: "",
                    coverageEndDate: "",
                    haveCoordinationBenefits: "",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000010",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000011",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000012",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000013",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000014",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000015",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000016",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
    {
        id: "PAT0000017",
        personal: {
            firstName: "Emran",
            middleName: "Alli",
            lastName: "Khan",
            gender: "Male",
            dob: "04/23/1985",
            maritalStatus: "Married",
            socialSecurityNumber: "906745375",
            homePhone: "+2349012345678",
            cellPhone: "",
            workPhone: "",
            preferredPhone: "",
            appointmentReminderMode: "Automated Email",
            email: "khan-allli@yahoo.com",
            sendMsgToHomePhone: "Yes",
            sendMsgToRelative: "No",
            sendMsgToWork: "No",
            sendMsgToCellPhone: "Yes",
            address: {
                streetName: "Cantebury Close",
                city: "Alexandr",
                state: "Potomac",
                zipCode: "123456",
            },
            highestEduLevel: "Masters",
            employmentStatus: "Employed",
            employer: "TeeHive Telecomms Services",
            occupation: "Engineer",
            religion: "Islam",
            ethnicity: "",
            race: "",
            preferredLanguage: "English",
        },
        guarantor: {
            firstName: "Sherif",
            // middleName: "",
            lastName: "Okunade",
            dob: "11/14/1972",
            relationship: "Supervisor",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            phone: "",
            email: "",
            stateIssuedId: "",
            insuranceCard: "",
        },
        parent: {
            firstName: "Julia",
            // middleName: "",
            lastName: "Michael",
            gender: "Female",
            maritalStatus: "Widow",
            phone: "",
            email: "",
            familyRole: "",
            employmentStatus: "",
            employer: "",
            occupation: "",
            address: { streetName: "", city: "", state: "", zipCode: "" },
        },
        emergency: {
            firstName: "MIchelle",
            // middleName: "",
            lastName: "Aladin",
            relationship: "Wife",
            address: { streetName: "", city: "", state: "", zipCode: "" },
            homePhone: "+41098765432",
            cellPhone: "",
            email: "",
        },
        insurance: {
            paymentMode: "Insurance Card",
            primaryInsurance: {
                policyHolder: {
                    firstName: "Emran",
                    middleName: "Alli",
                    lastName: "Khan",
                    relationship: "Self",
                    phone: "+41045454545",
                    dob: "04/14/1985",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "123455",
                    groupNumber: "127856",
                    authorizationId: "987612",
                    coPay: "12000",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                },
            },
            secondaryInsurance: {
                policyHolder: {
                    firstName: "Yushau",
                    middleName: "James",
                    lastName: "Kuban",
                    relationship: "Brother",
                    phone: "+41056345278",
                    dob: "10/10/1980",
                },
                insuranceProvider: {
                    name: "Medicare",
                    phone: "+41023232323",
                    policyId: "6389329",
                    groupNumber: "865392",
                    authorizationId: "3688567",
                    coverageStartDate: "02/13/2023",
                    coverageEndDate: "02/12/2026",
                    haveCoordinationBenefits: "Yes",
                    address: {
                        streetName: "",
                        city: "",
                        state: "",
                        zipCode: "",
                    },
                    coPay: "12000",
                },
            },
        },
        consent: { signature: "", date: "" },
    },
];

import { convertToUSDateTime } from "../utils";

export const appointments = [
    {
        id: "1",
        firstName: "James",
        middleName: "Joy",
        lastName: "Rodriguez",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab",
        dateTime: new Date().toISOString(),
        status: "Attended",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "2",
        firstName: "Adam",
        middleName: "Joy",
        lastName: "Smith",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Upcoming",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "3",
        firstName: "Bukola",
        middleName: "Joy",
        lastName: "Almarouf",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Missed",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "4",
        firstName: "Mushrif",
        middleName: "Joy",
        lastName: "Ajayi",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Attended",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    {
        id: "5",
        firstName: "Isabella",
        middleName: "Joy",
        lastName: "Evans",
        phone: "+4104567891",
        dob: "2025-02-13",
        gender: "Female",
        email: "username@gmail.com",
        streetAddress: "1 Example Street",
        city: "Example",
        state: "Example",
        zipCode: "123456",
        appointmentType: "In-person",
        service: "Medical Rehab",
        dateTime: "2025-02-13T14:30:00Z",
        status: "Upcoming",
        paymentMethod: "Insurance Card",
        insuranceName: "Medicare",
        insuranceNumber: "123456789",
    },
    // Add more data here
];

export const appointmentsColumns = [
    {
        accessorKey: "appointmentType",
        header: "Appointment Type",
    },
    {
        accessorKey: "dateTime",
        header: "Appointment Date",
        cell: (prop) => `${new Date(prop.getValue()).toLocaleString()}`,
    },
    // {
    //     accessorKey: "phone",
    //     header: "Phone",
    // },
    // {
    //     accessorKey: "email",
    //     header: "Email",
    // },
    {
        accessorKey: "status",
        header: "Status",
        cell: (prop) => {
            const value = prop.getValue();

            return (
                <span
                    className={`p-1 w-20 block text-center rounded text-xs text-offWhite capitalize ${
                        value.toLowerCase() === "attended"
                            ? "bg-lightGreen"
                            : value.toLowerCase() === "upcoming"
                            ? "bg-yellow-700"
                            : value.toLowerCase() === "missed"
                            ? "bg-vividRed"
                            : ""
                    }`}
                >
                    {value}
                </span>
            );
        },
    },
];

export const formDocs = [
    { id: 1, title: "Registration Form", url: "https://www.pleasantcarebhc.com/wp-content/themes/pleasantcareol/pdf/Patient_Information.pdf" },
    { id: 2, title: "Notice of Privacy Practices", url: "https://www.pleasantcarebhc.com/wp-content/themes/pleasantcareol/pdf/policy.pdf" },
];
